# Generated by Django 5.0.4 on 2024-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_student_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(max_length=20, null=True, verbose_name='speciality'),
        ),
    ]
