# Generated by Django 5.0.4 on 2024-04-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_alter_student_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
    ]
