# Generated by Django 5.0.4 on 2024-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0004_remove_teacher_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(max_length=100, null=True, verbose_name='Degree'),
        ),
    ]
