# Generated by Django 5.0.4 on 2024-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0005_remove_student_level_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses_of_interest',
            field=models.CharField(max_length=255, null=True, verbose_name='Courses of Interest'),
        ),
    ]
