# Generated by Django 5.0.4 on 2024-05-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0008_student_img_url_student_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img_url',
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
