# Generated by Django 5.0.4 on 2024-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0009_remove_student_img_url_student_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.AddField(
            model_name='student',
            name='img_url',
            field=models.URLField(blank=True, max_length=90, null=True),
        ),
    ]
