# Generated by Django 5.0.4 on 2024-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0010_remove_student_img_student_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img_url',
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
