# Generated by Django 5.0.4 on 2024-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0011_remove_course_img_url_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
        migrations.RemoveField(
            model_name='student',
            name='img_url',
        ),
        migrations.AddField(
            model_name='course',
            name='img_url',
            field=models.URLField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
