# Generated by Django 5.0.4 on 2024-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0012_remove_course_img_remove_student_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll_course',
            name='degree',
        ),
    ]
