# Generated by Django 5.0.4 on 2024-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0013_remove_enroll_course_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll_course',
            name='score_earned',
            field=models.IntegerField(default=0),
        ),
    ]
