# Generated by Django 5.0.4 on 2024-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0014_enroll_course_score_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='daily_time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='weekly_time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
