# Generated by Django 5.0.4 on 2024-05-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0015_student_daily_time_spent_student_monthly_time_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
